config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  resources :tags
  devise_for :users
  ActiveAdmin.routes(self)

  resources :posts
   get '/tags/:id/posts', to: 'posts#by_tag', as: 'posts_by_tag'
  root 'pokemons#index'

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    attr_accessor :tag_titles
    belongs_to :user
    validates :user, presence: true
    validates :title, presence: true
    validates :body, presence: true
    has_many :categorizations
    has_many :tags, through: :categorizations
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    validates :title, presence: true, uniqueness: true
    has_many :categorizations
    has_many :posts, through: :categorizations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :initialize_popular_tags

def initialize_popular_tags
  @popular_tags = Tag.all # don't worry, I know we don't want all tags! We'll come back to this later.
end
  def admin_required
    current_user.is_admin? || redirect_to('/')
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < InheritedResources::Base

  private

    def pokemon_params
      params.require(:pokemon).permit(:health, :attack, :defense, :special_attack, :special_defense, :speed, :title, :link)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
     tag_titles = @post.tags.map {|tag| tag.title }
     @post.tag_titles = tag_titles.join(',')
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post = current_user.posts.new(post_params)
    tags = get_tags(post_params[:tag_titles], ',')
    tags.each do |tag|
      @post.tags << tag
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      return head(:forbidden) unless @post.user == current_user
      tags = get_tags(post_params[:tag_titles], ',')
      @post.tags.clear
      tags.each do |tag|
        @post.tags << tag
      end
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
       return head(:forbidden) unless @post.user == current_user
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

# GET /tag/:id/posts - this comment helps you to remember which URL will map to this method
  def by_tag
    @tag = Tag.find(params[:id]) # remember, find will raise an error if the record is not found
    @posts = @tag.posts # get a list of all that tag's posts
  end

  private
    def get_tags(str, delim)
      titles = str.split(delim)
      tags = []
      titles.each do |title|
        title.strip!
        next unless title && title.length # we don't want to add blank tags
        tags << Tag.where(title: title).first_or_create
      end
      return tags
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :username, :string, :tag_titles)
    end
end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base

  private

    def tag_params
      params.require(:tag).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CS 290 Blog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <div class="notifications">
      <span class="notice"><%= notice %></span>
      <span class="alert"><%= alert %></span>
    </div>
    <ul class="login-links">
      <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>  
        </li>
      <% end %>
    </ul>
    <div class="clear"></div>
  </div>


  <div class="title">
    Who's your Favorite Pokemon?
  </div>
  <div class="container">

    <div class="content">
      <%= yield %>
    </div>
    <div class="clear"></div>
  </div>

</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :health %><br>
    <%= f.number_field :health %>
  </div>
  <div class="field">
    <%= f.label :attack %><br>
    <%= f.number_field :attack %>
  </div>
  <div class="field">
    <%= f.label :defense %><br>
    <%= f.number_field :defense %>
  </div>
  <div class="field">
    <%= f.label :special_attack %><br>
    <%= f.number_field :special_attack %>
  </div>
  <div class="field">
    <%= f.label :special_defense %><br>
    <%= f.number_field :special_defense %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.number_field :speed %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing a Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon, class: 'QQ' %> |
<%= link_to 'Back', pokemons_path, class: 'QQ' %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemon's Stats</h1>

<table>
  <thead>
    <tr class="stats">
      <th>Title</th>
      <th>Health</th>
      <th>Attack</th>
      <th>Defense</th>
      <th>Sp.Atk</th>
      <th>Sp.Def</th>
      <th>Speed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td>  <%= link_to(pokemon.title, pokemon.link) %></td>
        <td class="h"><%= pokemon.health %></td>
        <td class="a"><%= pokemon.attack %></td>
        <td class="d"><%= pokemon.defense %></td>
        <td class="sa"><%= pokemon.special_attack %></td>
        <td class="sd"><%= pokemon.special_defense %></td>
        <td class="s"><%= pokemon.speed %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path, class: 'QQ' %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= link_to(@pokemon.title, @pokemon.link) %>
</p>

<p class="Edit_H">
  <strong>Health:</strong>
  <%= @pokemon.health %>
</p>

<p class="Edit_A">
  <strong>Attack:</strong>
  <%= @pokemon.attack %>
</p>

<p class="Edit_D">
  <strong>Defense:</strong>
  <%= @pokemon.defense %>
</p>

<p class="Edit_SA">
  <strong>Sp.Atk:</strong>
  <%= @pokemon.special_attack %>
</p>

<p class="Edit_SD">
  <strong>Sp.Def:</strong>
  <%= @pokemon.special_defense %>
</p class="Edit_Stats">

<p class="Edit_S">
  <strong>Speed:</strong>
  <%= @pokemon.speed %>
</p>


<%= link_to 'Edit', edit_pokemon_path(@pokemon), class: 'QQ' %> |
<%= link_to 'Back', pokemons_path, class: 'QQ' %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tag_titles %><br>
    <%= f.text_field :tag_titles %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/by_tag.html.erb
<h1>Posts tagged "<%= @tag.title%>"</h1>

<% if @posts.empty? %>
  <p>No posts found.</p>
<% else %>
  <% @posts.each do |post| %>
    <p>
      <h3><%= post.title %> by <%= post.user.email %></h3>    
      <p><%= post.body %></p>
      <strong>Tags</strong>
      <ul>
        <% post.tags.each do |tag| %>
          <li><%= tag.title %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Username</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.username %></td>
        
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
<% if @post.tags %>
  <strong>Tags</strong>
  <ul>
  <% @post.tags.each do |tag| %>
    <li><%= tag.title %></li>
  <% end %>
  </ul>
<% end %>
<p>
  <strong>Username:</strong>
  <%= @post.username %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tag.title %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>